In [22]:
import torch

x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])
print(x)
print(y)

tensor([1, 2, 3])
tensor([4, 5, 6])


In [23]:
x+y

tensor([5, 7, 9])

In [24]:
x*y

tensor([ 4, 10, 18])

In [25]:
x/y

tensor([0.2500, 0.4000, 0.5000])

In [26]:
x**y

tensor([  1,  32, 729])

In [27]:
x-y

tensor([-3, -3, -3])

In [28]:
torch.dot(x,y)

tensor(32)

In [29]:
torch.matmul(x,y)


tensor(32)

In [32]:
x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([4,5,6])
print(x)
print(x.ndim)
print(y)
print(y.ndim)

tensor([[1, 2, 3],
        [4, 5, 6]])
2
tensor([4, 5, 6])
1


In [35]:
x*y

tensor([[ 4, 10, 18],
        [16, 25, 36]])