# 加载 fashion-mnist 数据集
batch size 为 256

In [1]:
import torch
from tqdm import tqdm
from torch import nn
import torchvision
from d2l import torch as d2l

In [ ]:
batch_size = 100

mnist_train, mnist_test =d2l.load_data_fashion_mnist(batch_size)

# 定义模型
图片的 size 为 28 * 28 = 784
输出是 10 个类别
把图片的像素转化为向量

In [ ]:
network = nn.Sequential(nn.Flatten(), nn.Linear(784, 10))

def init_weights(m):
    if type(m) == nn.Linear:
        nn.init.normal_(m.weight, std=0.01)

network.apply(init_weights)

loss_function = nn.CrossEntropyLoss()

optimizer = torch.optim.SGD(network.parameters(), lr=0.1)

def evaluate_accuracy(net, data_iter):  #@save
    """计算在指定数据集上模型的精度"""
    if isinstance(net, torch.nn.Module):
        net.eval()  # 将模型设置为评估模式
    metric = Accumulator(2)  # 正确预测数、预测总数
    with torch.no_grad():
        for X, y in data_iter:
            metric.add(accuracy(net(X), y), y.numel())
    return metric[0] / metric[1]

class Accumulator:  #@save
    """在n个变量上累加"""
    def __init__(self, n):
        self.data = [0.0] * n

    def add(self, *args):
        self.data = [a + float(b) for a, b in zip(self.data, args)]

    def reset(self):
        self.data = [0.0] * len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]
    
def accuracy(y_hat, y):  #@save
    """计算预测正确的数量"""
    if len(y_hat.shape) > 1 and y_hat.shape[1] > 1:
        y_hat = y_hat.argmax(axis=1)
    cmp = y_hat.type(y.dtype) == y
    return float(cmp.type(y.dtype).sum())

In [ ]:
epochs = 150
for epoch in range(epochs):
    network.train()
    total_loss = 0
    for X, y in tqdm(mnist_train, desc=f"Epoch {epoch+1}/{epochs}"):
        pred = network(X)
        loss = loss_function(pred, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    
    avg_loss = total_loss / len(mnist_train)
    print(f"Epoch {epoch+1}/{epochs}, Average Loss: {avg_loss:.4f}")

    # 可选：在验证集上评估
    network.eval()
    with torch.no_grad():
        evaluate_accuracy(network, mnist_test)
        

In [ ]:
torch.tensor([2, 3])

In [ ]:
torch.tensor([4., 2., 3.], requires_grad=True)

In [2]:
x = torch.tensor(([1,2], [2,3]), requires_grad=True, dtype=torch.float)
y = torch.tensor(([1, 2], [3, 4]), requires_grad=True, dtype=torch.float)
print(y)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [3]:
for i in range(2):
    y = torch.matmul(x, y)
    print(y)

tensor([[ 7., 10.],
        [11., 16.]], grad_fn=<MmBackward0>)
tensor([[29., 42.],
        [47., 68.]], grad_fn=<MmBackward0>)


In [4]:
z = torch.sum(y)
z.backward()

In [5]:

x.grad

tensor([[26., 48.],
        [32., 62.]])